import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Truco Score',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative flex flex-col min-h-screen">
          <div className="bg-custom-wood bg-cover bg-center fixed w-screen min-h-screen brightness-[.3]"></div>
          {children}
          <footer className="py-4 relative mt-auto text-gray-500 bottom-0 text-xs text-center w-full">
          Created with ♥ by <a href="https://www.linkedin.com/in/nicolas-de-horta/" className="underline underline-offset-2">Nicolas De Horta</a> &copy; {(new Date()).getFullYear()}
        </footer>
        </main>

      </body>
    </html>
  )
}
