import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Truco Score',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative flex flex-col h-screen overflow-hidden">
          <div className="bg-custom-wood bg-cover bg-center absolute w-screen h-screen brightness-[.3]"></div>
          {children}
        </main>
      </body>
    </html>
  )
}
